name = "Stitches Pack"
author = "Stitches"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f052ebd41f71daf48e331302259d3edf104bcc80fbe719b31b762a3a5fa4e08"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
